name: Build and Deploy
on:
  schedule:
    - cron: "0 4 * * *" 
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install and Build
        run: |
          pip install visivo
          visivo dist
          cp _redirects dist
        env:
          PYTEST_DB_PASSWORD: ${{secrets.PYTEST_DB_PASSWORD}}
          PYTEST_DB_USER: ${{secrets.PYTEST_DB_USER}}
          PYTEST_SNOWFLAKE_ACCOUNT: ${{secrets.PYTEST_SNOWFLAKE_ACCOUNT}}
          PYTEST_WAREHOUSE: ${{secrets.PYTEST_WAREHOUSE}}
          PYTEST_ROLE: ${{secrets.PYTEST_ROLE}}
          PYTEST_DB_SCHEMA: ${{secrets.PYTEST_DB_SCHEMA}}
          PYTEST_DATABASE: ${{secrets.PYTEST_DATABASE}}
          PYTEST_TABLE: ${{secrets.PYTEST_TABLE}}
          PYTEST_TARGET: ${{secrets.PYTEST_TARGET}}
          
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
